DROP DATABASE IF EXISTS TEST_SCIAC;

CREATE DATABASE TEST_SCIAC;

GRANT ALL PRIVILEGES ON TEST_SCIAC.* to zack@localhost IDENTIFIED BY 'rossman';

USE TEST_SCIAC;

CREATE TABLE FIELD_PLAYERS(
  cap_num VARCHAR(256) NOT NULL,
  name VARCHAR(256) NOT NULL,
  team VARCHAR(256) NOT NULL,
  shots INT NOT NULL,
  goalS INT NOT NULL,
  assists INT NOT NULL,
  points INT NOT NULL,
  exclusions INT NOT NULL,
  drawn_exc INT NOT NULL,
  steals INT NOT NULL
);

CREATE TABLE GOALIES(
  cap_num VARCHAR(256) NOT NULL,
  name VARCHAR(256) NOT NULL,
  team VARCHAR(256) NOT NULL,
  goals_allowed INT NOT NULL,
  saves INT NOT NULL,
  steals INT NOT NULL
);

CREATE TABLE GAMES(
 urls VARCHAR(256) NOT NULL
);
